"""Wind: a minimal PyTorch framework for WideNDepth-style models.

This is the high-level frontend package. Low-level building blocks
and kernels live in :mod:`winc`; FlashPKM access is provided
exclusively through :mod:`winc.pkm`.
"""

from .language import (
    LMConfig,
    LMOutput,
    LanguageModel,
    ReasoningState,
    LMTrainer,
    save_checkpoint,
    load_checkpoint,
)
from .api import (
    Config,
    KnowledgeTrainer,
    ModelBuilder,
    Regularizer,
    RegularizedTrainer,
    Trainer,
    TrainingContext,
    TrainingMetrics,
    Orthogonality,
    DiverseBank,
    build,
    configure,
)
from .wrap.sequential import Sequential
from .auxiliary import ByteTokenizer, TextCollator
from .lora import (
    LoRAConfig, AdapterTarget, LoRALinear, LoRAEmbedding, LoRAParameterization,
    DoRALinear, DoRAParameterization, PKMValueLoRA,
    discover_lora_targets, inject_lora, remove_lora, merge_lora, unmerge_lora,
    mark_only_lora_trainable, lora_parameters, lora_parameter_report,
    save_lora_adapters, load_lora_adapters,
)
from .profiling import (
    Profiler,
    ProfileConfig,
    profile,
    register_hook,
    metric,
    Summary,
    ArchitectureProfiler,
    LayerStats,
    ArchitectureSummary,
    LayerTreeSummary,
    LayerNode,
    KernelTrace,
    TraceEvent,
    Bottleneck,
    TimelineAnalyzer,
    TimelineRange,
    active,
    current,
    profile_memory,
    MemoryProfile,
    MemoryReport,
    format_memory_report,
    NCUProfiler,
    ncu_profile,
)

# Public symbols re-exported from winc (the WiNC backend).
from winc import (
    WindModule,
    Wide,
    WideStack,
    StageMode,
    apply_mode,
    Depth,
    FeedForward,
    RMSNorm,
    SwiGLU,
    RotaryEmbedding,
    RoPE,
    MLA,
    NSA,
    Attention,
    TransformerBlock,
    SparseBlock,
    Compressor,
    FeatureBank,
    Retrieval,
    ReasoningDepth,
    WideNDepth,
    EncoderDecoder,
    LearnedQueryCompressor,
    AdaptiveFeatureBank,
    LinearAdapter,
    TextAdapter,
    ImageAdapter,
    VideoAdapter,
    AudioAdapter,
    orthogonality_loss,
    diversity_loss,
    HardwareProfile,
    OptimizedBackend,
    optimize,
    Logger,
    console_logger,
    json_logger,
    make_logger,
    GenerationCache,
    LayerCache,
    CacheView,
    compile,
    CompileConfig,
    CompileProgress,
    get_compile_stats,
    reset_compile_stats,
    WindError,
    WindWarning,
    WindDeprecationWarning,
    WindAssertError,
    guard,
    assert_tensor,
    assert_finite,
    assert_dtype,
    assert_device,
    assert_shape,
    assert_shape_compatible,
    warn_sync,
    warn_dtype_mismatch,
    warn_device_mismatch,
    set_guard_enabled,
    set_guard_strict,
    assert_amp_compatible,
    assert_no_fp16_master_weights,
    assert_not_in_hot_path,
    assert_gradient_has_values,
    assert_loss_monotonically_decreasing,
    track_compile_start,
    check_compile_timeout,
    track_compile_end,
    reset_compile_tracker,
)

# FlashPKM access — always via winc.pkm, never imported directly by wind.
from winc.pkm import (
    make_pkm_wide,
    PKMAvailable as _PKMAvailable,
    pkm_available,
    FactorizedPKM,
    PKMWide,
    QueryEncoder,
)

pkm_kernels_available = pkm_available()

__all__ = [
    "Sequential", "Wide", "WideStack", "StageMode", "apply_mode",
    "AdaptiveFeatureBank", "Depth", "WindModule", "FeedForward",
    "MLA", "NSA", "RoPE", "RotaryEmbedding", "Attention",
    "TransformerBlock", "SparseBlock", "Compressor",
    "RMSNorm", "SwiGLU",
    "LinearAdapter", "TextAdapter", "ImageAdapter", "VideoAdapter", "AudioAdapter",
    "FeatureBank", "Retrieval", "ReasoningDepth", "WideNDepth",
    "EncoderDecoder", "LearnedQueryCompressor",
    "orthogonality_loss", "diversity_loss",
    "HardwareProfile", "OptimizedBackend", "optimize",
    "compile", "CompileConfig", "CompileProgress", "get_compile_stats",
    "reset_compile_stats",
    "Logger", "console_logger", "json_logger", "make_logger",
    "GenerationCache", "LayerCache", "CacheView",
    "FactorizedPKM", "PKMWide", "QueryEncoder", "pkm_kernels_available",
    "Config", "build", "configure", "Trainer", "KnowledgeTrainer",
    "ModelBuilder", "Regularizer", "Orthogonality", "DiverseBank",
    "RegularizedTrainer", "TrainingContext", "TrainingMetrics",
    "LMConfig", "LMOutput", "LanguageModel", "ReasoningState", "LMTrainer",
    "save_checkpoint", "load_checkpoint",
    "ByteTokenizer", "TextCollator",
    "LoRAConfig", "AdapterTarget", "LoRALinear", "LoRAEmbedding", "LoRAParameterization",
    "DoRALinear", "DoRAParameterization", "PKMValueLoRA",
    "discover_lora_targets", "inject_lora", "remove_lora", "merge_lora", "unmerge_lora",
    "mark_only_lora_trainable", "lora_parameters", "lora_parameter_report",
    "save_lora_adapters", "load_lora_adapters",
    "Profiler", "ProfileConfig", "profile", "register_hook", "metric", "Summary",
    "ArchitectureProfiler", "LayerStats", "ArchitectureSummary",
    "LayerTreeSummary", "LayerNode", "KernelTrace", "TraceEvent",
    "Bottleneck", "TimelineAnalyzer", "TimelineRange",
    "NCUProfiler", "ncu_profile",
    "active", "current", "profile_memory", "MemoryProfile", "MemoryReport",
    "format_memory_report",
    "WindError", "WindWarning", "WindDeprecationWarning", "WindAssertError",
    "guard", "assert_tensor", "assert_finite", "assert_dtype", "assert_device",
    "assert_shape", "assert_shape_compatible", "warn_sync", "warn_dtype_mismatch",
    "warn_device_mismatch", "set_guard_enabled", "set_guard_strict",
    "assert_amp_compatible", "assert_no_fp16_master_weights", "assert_not_in_hot_path",
    "assert_gradient_has_values", "assert_loss_monotonically_decreasing",
    "track_compile_start", "check_compile_timeout", "track_compile_end",
    "reset_compile_tracker",
]

__version__ = "2.1.0"


